services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - ./env/vaultwarden.env
    ports:
      - "8080:80"
    volumes:
      - /mnt/ssd/nas/bitwarden-data/vaultwarden:/data
